name: territoriei
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.4.0
  equatable: ^2.0.3
  empty_widget: ^0.0.5
  google_fonts: ^2.3.1
  country_codes: ^2.1.1
  flutter_bloc: ^8.0.1
  logging: ^1.0.2
  uuid: ^3.0.5
  flag:
    git:
      url: https://github.com/LunaGao/flag_flutter
      ref: fb4e37df8f890500faa8def830a1080dda92a09a
  url_launcher: ^6.0.18
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.0.1
  firebase_core: ^1.12.0
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  lints: ^1.0.1
  mockito: ^5.0.17
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  fast_i18n: ^5.10.0
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/svgs/
    - lib/assets/images/

  
